"""Modified models

Revision ID: 1a1cf2422d11
Revises: e4c400b6461d
Create Date: 2018-06-23 21:36:16.630794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1cf2422d11'
down_revision = 'e4c400b6461d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistic_regression_model', sa.Column('use_me', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistic_regression_model', 'use_me')
    # ### end Alembic commands ###
