"""empty message

Revision ID: 60e8f11700c5
Revises: 
Create Date: 2018-09-21 02:53:33.200679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e8f11700c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initial_training_dataDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=10000), nullable=True),
    sa.Column('positive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logistic_regression_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.LargeBinary(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('vectorizer', sa.LargeBinary(), nullable=True),
    sa.Column('use_me', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweetDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_id', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twitter_id')
    )
    op.create_index(op.f('ix_tweetDB_name'), 'tweetDB', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('youtube_videoDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoid', sa.String(length=12), nullable=True),
    sa.Column('title', sa.String(length=70), nullable=True),
    sa.Column('caption', sa.String(length=10000), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_videoDB_title'), 'youtube_videoDB', ['title'], unique=False)
    op.create_index(op.f('ix_youtube_videoDB_videoid'), 'youtube_videoDB', ['videoid'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_youtube_videoDB_videoid'), table_name='youtube_videoDB')
    op.drop_index(op.f('ix_youtube_videoDB_title'), table_name='youtube_videoDB')
    op.drop_table('youtube_videoDB')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tweetDB_name'), table_name='tweetDB')
    op.drop_table('tweetDB')
    op.drop_table('logistic_regression_model')
    op.drop_table('initial_training_dataDB')
    # ### end Alembic commands ###
