"""Added correct to TweetDB and YoutubeVideoDB

Revision ID: 6322d7fc4b78
Revises: 1a1cf2422d11
Create Date: 2018-06-24 00:28:31.758463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6322d7fc4b78'
down_revision = '1a1cf2422d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweetDB', sa.Column('correct', sa.Boolean(), nullable=True))
    op.add_column('youtube_videoDB', sa.Column('correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_videoDB', 'correct')
    op.drop_column('tweetDB', 'correct')
    # ### end Alembic commands ###
