"""Added Youtube Videos

Revision ID: 7bb34d2bec5c
Revises: 4ef9e018fe01
Create Date: 2018-06-06 13:30:49.700003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb34d2bec5c'
down_revision = '4ef9e018fe01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_videoDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoid', sa.String(length=12), nullable=True),
    sa.Column('title', sa.String(length=70), nullable=True),
    sa.Column('caption', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_videoDB_title'), 'youtube_videoDB', ['title'], unique=False)
    op.create_index(op.f('ix_youtube_videoDB_videoid'), 'youtube_videoDB', ['videoid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_videoDB_videoid'), table_name='youtube_videoDB')
    op.drop_index(op.f('ix_youtube_videoDB_title'), table_name='youtube_videoDB')
    op.drop_table('youtube_videoDB')
    # ### end Alembic commands ###
