"""Added Tweet

Revision ID: 965fdc038f23
Revises: 7aeaa93d23d6
Create Date: 2018-06-11 20:56:48.227583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965fdc038f23'
down_revision = '7aeaa93d23d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweeter', sa.String(length=12), nullable=True),
    sa.Column('content', sa.String(length=280), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_tweeter'), 'tweet', ['tweeter'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweet_tweeter'), table_name='tweet')
    op.drop_table('tweet')
    # ### end Alembic commands ###
