"""Switched tweetid to be string instead of integer

Revision ID: a77f954e2328
Revises: d2349a849849
Create Date: 2018-06-24 20:38:50.588120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77f954e2328'
down_revision = 'd2349a849849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tweetDB_twitter_id'), 'tweetDB', ['twitter_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweetDB_twitter_id'), table_name='tweetDB')
    # ### end Alembic commands ###
