"""Added TweetDB

Revision ID: c0d2a3ecd6ca
Revises: 7aeaa93d23d6
Create Date: 2018-06-21 18:26:27.419533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d2a3ecd6ca'
down_revision = '7aeaa93d23d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweetDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweetDB_name'), 'tweetDB', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweetDB_name'), table_name='tweetDB')
    op.drop_table('tweetDB')
    # ### end Alembic commands ###
