"""Added vectorizer to LogisticRegressionModeL

Revision ID: d2349a849849
Revises: 6322d7fc4b78
Create Date: 2018-06-24 15:55:48.686630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2349a849849'
down_revision = '6322d7fc4b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistic_regression_model', sa.Column('vectorizer', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistic_regression_model', 'vectorizer')
    # ### end Alembic commands ###
