"""Added InitialTrainingDataDB and LogisticRegressionModel

Revision ID: e4c400b6461d
Revises: c0d2a3ecd6ca
Create Date: 2018-06-23 12:33:15.645287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c400b6461d'
down_revision = 'c0d2a3ecd6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initial_training_dataDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=10000), nullable=True),
    sa.Column('positive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logistic_regression_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.LargeBinary(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logistic_regression_model')
    op.drop_table('initial_training_dataDB')
    # ### end Alembic commands ###
